/**
 * Worker homepage keeps custody chrome and adds the suite Live Nodes strip.
 */
import assert from "node:assert/strict";
import { homeHtml } from "../workers/download-tracker/src/ui.js";
import { LIVE_NODES_COPY, QNS_CD, QNM_BUILD } from "../workers/download-tracker/src/mesh.js";

const html = homeHtml({ views: 1, downloads: 2, github: { stars: 0 } });

assert.match(html, /id="nodes"/);
assert.match(html, /Live Nodes/);
assert.match(html, /Mesh ON/);
assert.equal(html.includes("Mesh OFF"), false);
assert.equal(html.includes("MESH_OFF"), false);
assert.equal(/mesh-off/i.test(html), false);
assert.equal(html.includes("/v1/mesh/disable"), false);
assert.equal(/disable button/i.test(html), false);
assert.match(html, /QNM-BUILD-1.0/);
assert.match(html, /QNS-CD-1.0/);
assert.match(html, /live\|locked\|isolated/);
assert.match(html, /AIH-WP-1.3 spiderweb is local qnm-node/);
assert.match(html, /not a public Node Gate/);
assert.match(html, /GET never enables/);
assert.match(html, /SPLIT THE WIRES/);
assert.match(html, /COLD-COPY SURVIVAL/);
assert.match(html, /REHEAL refuse/);
assert.match(html, /never share a socket/);
assert.match(html, /refuse live body sync/);
assert.match(html, /no neighbor vote-to-fix/);
assert.match(html, /qnsd/);
assert.equal(QNS_CD, "QNS-CD-1.0");
assert.equal(QNM_BUILD, "QNM-BUILD-1.0");
assert.match(LIVE_NODES_COPY, /QNS-CD-1.0/);
assert.match(LIVE_NODES_COPY, /QNM-BUILD-1.0/);
assert.match(LIVE_NODES_COPY, /Live Nodes/);
assert.match(LIVE_NODES_COPY, /SPLIT THE WIRES/);
assert.match(LIVE_NODES_COPY, /COLD-COPY SURVIVAL/);
assert.match(LIVE_NODES_COPY, /REHEAL refuse/);
assert.equal(LIVE_NODES_COPY.includes("Mesh OFF"), false);
assert.equal(/default off/i.test(LIVE_NODES_COPY), false);
assert.match(html, /pair-offer-btn/);
assert.match(html, /pair_offer/);
assert.match(html, /not anonymity/);
assert.match(html, /not a publish path/);
assert.match(html, /\/v1\/mesh\/status/);
assert.match(html, /\/v1\/mesh\/nodes/);
assert.match(html, /no auto-heal/);
assert.match(html, /product: MESH_PRODUCT/);
assert.match(html, /azinterface/);
assert.match(html, /Live Nodes read-only/);
assert.equal(/Default OFF/.test(html.split('id="nodes"')[1]?.split("</footer>")[0] || html), false);

assert.match(html, /data-state="ON"/);
assert.match(html, /data-state="OFF"/);
assert.match(html, /data-state="FULL_SHUTDOWN"/);
assert.match(html, /data-state="MEMORIAL"/);
assert.match(html, /genesis-btn/);
assert.match(html, /integrity-btn/);
assert.match(html, /witness-btn/);
assert.match(html, /withdraw-btn/);
assert.match(html, /PRE-LOCKED/);
assert.match(html, /AZHome bunker/);
assert.match(html, /Scorched Earth/);
assert.match(html, /page_cycle_status/);
assert.match(html, /LOCKED pipeline/);
assert.match(html, /THE SINGLE DOOR/);
assert.match(html, /Internal Domain Layer/);
assert.match(html, /No LambGate/);
assert.match(html, /out-panel/);
assert.match(html, /function humanLines/);
assert.match(html, /This request was refused/);
assert.equal(html.includes("Full JSON"), false);
assert.match(html, /Copy install steps/);
assert.equal(html.includes("One-click install"), false);
assert.match(html, /Softwares 42 is the runtime catalog/);
assert.match(html, /The domain count stays 33/);
assert.match(html, /The packet path is not live/);
assert.match(html, /The alternative internet is not live/);
assert.match(html, /Still missing: a packet that leaves this machine and arrives on a different machine id/);
assert.match(html, /LAN hardware is absent/);
assert.match(html, /Cap-7 and \.aziel stay names only/);
assert.match(html, /WARN-5 stands/);
assert.match(html, /Mail send does not run on the public worker/);
assert.match(html, /The public worker does not run a kernel/);
assert.match(html, /Boot does not run on the public worker/);
assert.match(html, /The host operating system stays the host operating system/);
assert.match(html, /AZNews can stand alone/);
assert.match(html, /4DMap can stand alone/);
assert.equal(html.includes("Internet is not live"), false);
assert.equal(html.includes("not a live map"), false);
assert.match(html, /max-height:12rem/);
assert.match(html, /install-steps/);
assert.match(html, /install-advanced/);
assert.match(html, /Checksum note/);
assert.match(html, /custody UI only/);
assert.match(html, /Agents use aziel-runtime FragGate\/MCP/);
assert.match(html, /AZCoherence/);
assert.match(html, /slug=azcoherence/);
assert.match(html, /AZ-CLCE/);
assert.match(html, /cite\.json/);
assert.match(html, /azcoherence-download-tracker/);
assert.match(html, /GET \/v1\/software/);
assert.match(html, /plain A–Z/);
assert.match(html, /install\.sh -o install-azinterface\.sh/);
assert.match(html, /toastMemorial/);
assert.match(html, /AIH-CYCLE-TERMINAL/);
assert.match(html, /MEMORIAL is terminal/);
assert.equal(html.includes("curl -fsSL") && html.includes("| bash"), true);
const installCmd = (html.match(/id="install-cmd">([\s\S]*?)<\/pre>/) || [])[1] || "";
assert.match(installCmd, /install\.sh -o install-azinterface\.sh/);
assert.equal(installCmd.includes("| bash"), false);

console.log("worker ui mesh strip ok");
